export const servicios = [
  {
    id: "camara",
    imgHome: "/img/fotoServicioCamaras.webp",
    imgServicios: "/img/camaraServicios.jpg",
    titleHome: "Cámaras de monitoreo",
    bgIconHome: "bg-primary",
    fillIconHome: "fill-primary",
    titleServicios: "Cámaras de Monitoreo en Tiempo Real",
    subtitleServicios: "Siempre cerca de tu hijo, estés donde estés",
    descripHome:
      "El jardín cuenta con servicio de monitoreo en vivo mediante cámaras de seguridad permitiendo a los padres vigilar a sus hijos en tiempo real.",
    descripServicios:
      "En nuestro jardín infantil entendemos que la tranquilidad de los padres es tan importante como el bienestar de los niños. Por eso, contamos con un sistema de cámaras de seguridad con transmisión en vivo, al que podrás acceder de manera sencilla desde tu teléfono móvil mediante una aplicación exclusiva.",
    hrefHome: "/servicios",
    iconHome: "camara",
    icon1Servicios: "/img/camarasServiceMonster.png",
    icon2Servicios: "/img/vector-randall.svg",
    left: false,
    bg: true,
    bg2: false,
  },
  {
    id: "ingles",
    imgHome: "/img/fotoServicioclassIngles.webp",
    imgServicios: "/img/inglesServicios.jpg",
    titleHome: "Ingles Intensivo",
    bgIconHome: "bg-secondary",
    fillIconHome: "fill-secondary",
    titleServicios: "Inglés Intensivo",
    subtitleServicios: "El idioma del mundo al alcance de los niños",
    descripHome:
      "Aprender inglés desde una edad temprana fortalece el desarrollo mental y habilidades como la creatividad, el pensamiento crítico y la resolución de problemas.",
    descripServicios:
      "En HOWARD GARDNER, sabemos que el aprendizaje de un segundo idioma desde la primera infancia abre puertas y fortalece el desarrollo cognitivo de los niños. Por ello, contamos con un programa de inglés intensivo diseñado especialmente para que los pequeños aprendan de forma natural, divertida y significativa, al integrar el idioma en sus rutinas diarias a través de canciones, juegos, cuentos, dramatizaciones y actividades interactivas que estimulan la curiosidad y la participación activa.",
    hrefHome: "/servicios",
    iconHome: "ingles",
    icon1Servicios: "/img/inglesServiceMonster.png",
    icon2Servicios: "/img/Vector.png",
    left: true,
    bg: false,
    bg2: true,
  },
  {
    id: "psicologia",
    imgHome: "/img/fotoServicioPsicologia.webp",
    imgServicios: "/img/psicologiaServicios.jpg",
    titleHome: "Profesional de Psicologia",
    titleServicios: "Psicología Infantil",
    bgIconHome: "bg-primary",
    fillIconHome: "fill-primary",
    subtitleServicios: "Creciendo con emociones sanas",
    descripHome:
      "La psicología es clave en esta etapa porque guía a los niños en su desarrollo emocional y social. En el jardín se diseña mensualmente un menú adaptado a sus necesidades.",
    descripServicios:
      "Reconocemos que el desarrollo emocional en los niños es tan importante como el académico. Por eso, en nuestro jardin, contamos con el servicio de psicología profesional, enfocado en acompañar a los niños de manera individual y brindar apoyo a las familias cuando es necesario. El objetivo es favorecer el bienestar integral de cada niño, potenciando sus habilidades sociales, su autoestima y la gestión adecuada de sus emociones, en un ambiente lleno de respeto y afecto.",
    hrefHome: "/servicios",
    iconHome: "psicologia",
    icon1Servicios: "/img/psicologiaServiceMonter.png",
    icon2Servicios: "/img/vector-randall.svg",
    left: false,
    bg: true,
    bg2: false,
  },
  {
    id: "nutricion",
    imgHome: "/img/fotoServicioNutricion.webp",
    imgServicios: "/img/nutricionServicios.jpg",
    titleHome: "Nutrición Infantil",
    titleServicios: "Nutrición Balanceada",
    bgIconHome: "bg-secondary",
    fillIconHome: "fill-secondary",
    subtitleServicios: "Alimentamos cuerpos sanos y mentes brillantes",
    descripHome:
      "Contamos con el acompañamiento de una nutricionista profesional que vela por el bienestar y crecimiento de cada niño, haciendo un seguimiento constante a su alimentación, talla y peso.",
    descripServicios:
      "Contamos con un equipo profesional de nutricionistas que realizan un seguimiento constante de talla y peso en cada niño, con el fin de garantizar su avance de acuerdo con su edad y etapa de crecimiento, pues sabemos que una buena alimentación es la base para el crecimiento saludable y el aprendizaje pleno de los niños. En base a nuestro plan de seguimiento diseñamos menús balanceados y personalizados que responden a sus necesidades nutricionales, siempre bajo criterios de calidad, variedad y equilibrio.",
    hrefHome: "/servicios",
    iconHome: "nutricion",
    icon1Servicios: "/img/nutriconServiceMonster.png",
    icon2Servicios: "/img/Vector.png",
    left: true,
    bg: false,
    bg2: true,
  },
  {
    id: "ruta",
    imgHome: "/img/fotoServicioRuta.webp",
    imgServicios: "/img/rutaEscolarServicios.webp",
    titleHome: "Ruta Escolar",
    titleServicios: "Transporte Escolar Seguro y Confiable",
    bgIconHome: "bg-primary",
    fillIconHome: "fill-primary",
    subtitleServicios:
      "De la casa al Jardín y retorno a casa, una experiencia segura y tranquila",
    descripHome:
      "Ofrecemos un servicio de ruta escolar seguro y confiable, con personal capacitado y vehículo adaptado para el transporte de niños, garantizando tranquilidad y comodidad a los padres.",
    descripServicios:
      "Nuestro servicio de ruta escolar brinda confianza y tranquilidad a las familias. Acompañamos a los niños en cada trayecto para que lleguen puntuales, tranquilos y listos para disfrutar de su día en el jardín y su retorno a casa",
    hrefHome: "/servicios",
    iconHome: "ruta",
    icon1Servicios: "/img/rutaServiceMonster.webp",
    icon2Servicios: "/img/Vector.png",
    left: false,
    bg: true,
    bg2: false,
  },
];
